export const PROJECT_IMAGES = {
  //Application Projects
  GKeep: {
    desktop: [""],
    phone: [
      "/img/GKeep/GKeep_SS0.jpg",
      "/img/GKeep/GKeep_SS1.0.jpg",
      "/img/GKeep/GKeep_SS1.1.jpg",
      "/img/GKeep/GKeep_SS1.2.jpg",
      "/img/GKeep/GKeep_SS1.3.jpg",
      "/img/GKeep/GKeep_SS2.jpg",
      "/img/GKeep/GKeep_SS3.0.jpg",
      "/img/GKeep/GKeep_SS3.1.jpg",
      "/img/GKeep/GKeep_SS3.2.jpg",
      "/img/GKeep/GKeep_SS4.jpg",
      "/img/GKeep/GKeep_SS5.jpg",
    ],
  },
  BalingTech: {
    desktop: [""],
    phone: [
      "/img/BalingTech/BalingTech_SS0.jpg",
      "/img/BalingTech/BalingTech_SS1.0.jpg",
      "/img/BalingTech/BalingTech_SS1.1.jpg",
      "/img/BalingTech/BalingTech_SS1.2.jpg",
      "/img/BalingTech/BalingTech_SS1.3.jpg",
      "/img/BalingTech/BalingTech_SS2.0.jpg",
      "/img/BalingTech/BalingTech_SS2.1.jpg",
      "/img/BalingTech/BalingTech_SS2.2.jpg",
      "/img/BalingTech/BalingTech_SS3.jpg",
    ],
  },
  Pinyaxtract: {
    desktop: [""],
    phone: [
      "/img/Pinyaxtract/Pinyaxtract_SS0.jpg",
      "/img/Pinyaxtract/Pinyaxtract_SS1.jpg",
      "/img/Pinyaxtract/Pinyaxtract_SS2.jpg",
      "/img/Pinyaxtract/Pinyaxtract_SS3.jpg",
      "/img/Pinyaxtract/Pinyaxtract_SS4.0.jpg",
      "/img/Pinyaxtract/Pinyaxtract_SS4.1.1.jpg",
      "/img/Pinyaxtract/Pinyaxtract_SS4.1.2.jpg",
      "/img/Pinyaxtract/Pinyaxtract_SS4.1.3.jpg",
      "/img/Pinyaxtract/Pinyaxtract_SS5.0.jpg",
      "/img/Pinyaxtract/Pinyaxtract_SS5.1.jpg",
      "/img/Pinyaxtract/Pinyaxtract_SS5.2.jpg",
      "/img/Pinyaxtract/Pinyaxtract_SS5.3.jpg",
    ],
  },

  //Website Projects

  BananaCare: {
    desktop: [
      "/img/Bananacare/Bananacare_SS0.jpg",
      "/img/Bananacare/Bananacare_SS1.0.0.jpg",
      "/img/Bananacare/Bananacare_SS1.0.1.jpg",
      "/img/Bananacare/Bananacare_SS1.0.2.jpg",
      "/img/Bananacare/Bananacare_SS1.0.3.jpg",
      "/img/Bananacare/Bananacare_SS1.0.4.jpg",
      "/img/Bananacare/Bananacare_SS1.2.0.jpg",
      "/img/Bananacare/Bananacare_SS1.3.0.jpg",
      "/img/Bananacare/Bananacare_SS1.4.0.jpg",
      "/img/Bananacare/Bananacare_SS2.0.0.jpg",
      "/img/Bananacare/Bananacare_SS2.1.0.jpg",
      "/img/Bananacare/Bananacare_SS2.2.0.jpg",
    ],
    phone: [
      "/img/Bananacare/BananacarePhone_SS0.jpg",
      "/img/Bananacare/BananacarePhone_SS1.0.0.jpg",
      "/img/Bananacare/BananacarePhone_SS1.0.1.jpg",
      "/img/Bananacare/BananacarePhone_SS1.0.2.jpg",
      "/img/Bananacare/BananacarePhone_SS1.0.3.jpg",
      "/img/Bananacare/BananacarePhone_SS1.0.4.jpg",
      "/img/Bananacare/BananacarePhone_SS1.1.0.jpg",
      "/img/Bananacare/BananacarePhone_SS1.2.0.jpg",
      "/img/Bananacare/BananacarePhone_SS1.3.0.jpg",
      "/img/Bananacare/BananacarePhone_SS1.4.0.jpg",
      "/img/Bananacare/BananacarePhone_SS2.0.jpg",
      "/img/Bananacare/BananacarePhone_SS2.1.jpg",
      "/img/Bananacare/BananacarePhone_SS2.2.jpg",
    ],
  },
  BeeWatch: {
    desktop: [
      "/img/BeeWatch/BeeWatch_SS0.jpg",
      "/img/BeeWatch/BeeWatch_SS1.0.jpg",
      "/img/BeeWatch/BeeWatch_SS1.1.jpg",
      "/img/BeeWatch/BeeWatch_SS1.2.jpg",
      "/img/BeeWatch/BeeWatch_SS1.3.jpg",
      "/img/BeeWatch/BeeWatch_SS2.0.jpg",
      "/img/BeeWatch/BeeWatch_SS2.1.jpg",
      "/img/BeeWatch/BeeWatch_SS2.2.jpg",
      "/img/BeeWatch/BeeWatch_SS3.0.jpg",
      "/img/BeeWatch/BeeWatch_SS3.1.jpg",
      "/img/BeeWatch/BeeWatch_SS4.jpg",
      "/img/BeeWatch/BeeWatch_SS5.jpg",
    ],
    phone: [
      "/img/BeeWatch/BeeWatchPhone_SS0.jpg",
      "/img/BeeWatch/BeeWatchPhone_SS1.0.jpg",
      "/img/BeeWatch/BeeWatchPhone_SS1.1.jpg",
      "/img/BeeWatch/BeeWatchPhone_SS1.2.jpg",
      "/img/BeeWatch/BeeWatchPhone_SS1.3.jpg",
      "/img/BeeWatch/BeeWatchPhone_SS1.4.jpg",
      "/img/BeeWatch/BeeWatchPhone_SS2.jpg",
      "/img/BeeWatch/BeeWatchPhone_SS3.jpg",
    ],
  },
  Envirometrix: {
    desktop: [
      "/img/Enviromentrix/Enviromentrix_SS0.jpg",
      "/img/Enviromentrix/Enviromentrix_SS1.0.jpg",
      "/img/Enviromentrix/Enviromentrix_SS1.1.jpg",
      "/img/Enviromentrix/Enviromentrix_SS2.jpg",
      "/img/Enviromentrix/Enviromentrix_SS3.jpg",
    ],
    phone: [
      "/img/Enviromentrix/EnviromentrixPhone_SS0.jpg",
      "/img/Enviromentrix/EnviromentrixPhone_SS1.0.jpg",
      "/img/Enviromentrix/EnviromentrixPhone_SS1.1.jpg",
      "/img/Enviromentrix/EnviromentrixPhone_SS2.jpg",
      "/img/Enviromentrix/EnviromentrixPhone_SS3.jpg",
    ],
  },
};
